#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           20

bspc config split_ratio          0.50
bspc config top_padding          0
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=floating focus=on rectangle=1024x1296+0+0 center=true
bspc rule -a Firefox state=pseudo_tiled focus=on

pgrep -x redshift-gtk > /dev/null || redshift-gtk &
feh --bg-scale /usr/share/pixmaps/wallpaper.jpg
pgrep -x picom > /dev/null || picom &
pgrep polkit-gnome > /dev/null || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
~/.config/polybar/launch.sh &
